### ISSUE TITLE
FINOS Review - Contribution Compliance Requirements for FINOS Contribution

### ISSUE THREAD

**Issue by mcleo-d** [finos/TimeBase-CE#1]
## Description
Following a quick review of the TimeBase project prior to FINOS contribution, this issue describes prerequisites needed within the open source project as outlined in the Contribution Compliance Requirements document below ... 

- https://finosfoundation.atlassian.net/wiki/spaces/FINOS/pages/75530375/Contribution+Compliance+Requirements

**Please Note :** The relevant information should also be included in the dependencies consumed by TimeBase as hosted in the EPAM (or other) GitHub Organisation - https://github.com/epam?q=timebase&type=&language=&sort=

### [License Information](https://finosfoundation.atlassian.net/wiki/spaces/FINOS/pages/75530375/Contribution+Compliance+Requirements#ContributionComplianceRequirements-LicenseInformation)
- [The LICENSE file](https://finosfoundation.atlassian.net/wiki/spaces/FINOS/pages/75530375/Contribution+Compliance+Requirements#ContributionComplianceRequirements-TheLICENSEfile)
- [The NOTICE file](https://finosfoundation.atlassian.net/wiki/spaces/FINOS/pages/75530375/Contribution+Compliance+Requirements#ContributionComplianceRequirements-TheNOTICEfile)
- [The CONTRIBUTING file](https://finosfoundation.atlassian.net/wiki/spaces/FINOS/pages/75530375/Contribution+Compliance+Requirements#ContributionComplianceRequirements-TheCONTRIBUTINGfile)
- [Source code license headers](https://finosfoundation.atlassian.net/wiki/spaces/FINOS/pages/75530375/Contribution+Compliance+Requirements#ContributionComplianceRequirements-Sourcecodelicenseheaders)
- [SPDX information](https://finosfoundation.atlassian.net/wiki/spaces/FINOS/pages/75530375/Contribution+Compliance+Requirements#ContributionComplianceRequirements-SPDXinformation)

### [Third-Party Code Compliance](https://finosfoundation.atlassian.net/wiki/spaces/FINOS/pages/75530375/Contribution+Compliance+Requirements#ContributionComplianceRequirements-Third-PartyCodeCompliance)
- [Identifying acceptable licenses](https://finosfoundation.atlassian.net/wiki/spaces/FINOS/pages/75530375/Contribution+Compliance+Requirements#ContributionComplianceRequirements-Identifyingacceptablelicenses)
- [Including required third-party notices](https://finosfoundation.atlassian.net/wiki/spaces/FINOS/pages/75530375/Contribution+Compliance+Requirements#ContributionComplianceRequirements-Includingrequiredthird-partynotices)

cc @stuartfarr, @avavilau, @alex-karpovich, @cm-howard

**Comment by fatiherikli** [comment]
What is that exactly?
