### ISSUE TITLE
TimeBase Contribution Steps into FINOS

### ISSUE THREAD

**Issue by mcleo-d** [finos/TimeBase-CE#2]
## Description
This issue describes the items needed to be done to complete the Timebase contribution into FINOS.

- [x] @alex-karpovich to archive [DeltixInc Timebase](https://github.com/DeltixInc/TimeBase) repository whilst adding a link to [FINOS timebase-ce](https://github.com/finos/timebase-ce) in the archived [DeltixInc Timebase README.md](https://github.com/DeltixInc/TimeBase/blob/master/README.md).
- [x] @cm-howard to provide @maoo latest compliance check report to understand current state of [EPAM Timebase](https://github.com/epam/TimeBase) project.
- [x] @alex-karpovich to review #1 against [EPAM Timebase](https://github.com/epam/TimeBase) repo and dependencies consumed by project.
  - Please note that https://github.com/finos/timebase-ce contains template files that correspond with the items listed in #1 
  - [ ] TimeBaseClientCpp
  - [ ] TimebaseWS
  - [ ] TimeBaseClientPython
  - [ ] TimeBaseCommons
  - [ ] TimeBaseClickhouseConnector
  - [ ] TimeBaseTimescaleConnector
  - [ ] TimeBaseKafkaConnector
  - [ ] TimeBaseCluster
  - [ ] TimeBaseClient.Net
  - [ ] TimeBaseTutorial
- [x] @alex-karpovich to update [EPAM Timebase README.md](https://github.com/epam/TimeBase/blob/main/readme.md) using [FINOS Timebase contribution issue](https://github.com/finos/community/issues/70) as template https://github.com/finos/community/issues/70 cc @stuartfarr
- [x] @maoo to conduct validation checks from [EPAM Timebase](https://github.com/epam/TimeBase) project when given the okay by @alex-karpovich.
- [x] @alex-karpovich to determine whether [EPAM Timebase](https://github.com/epam/TimeBase) project should be contributed to FINOS via direct commit to [FINOS timebase-ce](https://github.com/finos/timebase-ce) or transfered from EPAM to FINOS organisation.

**Comment by cm-howard** [comment]
Confirming that @alex-karpovich has provided the compliance reports and therefore I've marked this task as completed.

**Comment by maoo** [comment]
All done here, closing issue. Thanks!
