### ISSUE TITLE
Aggregating tick by tick data to 1-Minute bars 

### ISSUE THREAD

**Issue by vgwSol** [finos/TimeBase-CE#215]
is it possible to generate a new stream (1 minute bar/aggregation) from streaming tick by tick data ?

**Comment by alex-karpovich** [comment]
yes, this is possible using QQL and aggregates

```
SELECT
sum{}(size) AS 'volume',
first{}(price) AS 'open',
last{}(price) AS 'close',
max{}(price) AS 'high',
min{}(price) AS 'low'

FROM LIVE(trades)
OVER TIME(1m)
```

Details here:
https://kb.timebase.info/community/development/qql/QQL%205.5/qql-tut-functions#stateful-functions

**Comment by vgwSol** [comment]
Seems it is on-demand aggregation 

Take a scenario : 

1. Timabase have 1 Month of tick by tick data and realtime data is also streaming in.
2. Now I want 1 minutes bars of a symbol/ticker for last 30days and then streaming 1 minute bars
3. If I use above query approach then TimeBase need to scroll all the old data and create bars and start continuous query
4. Lets say now someone else ask for same symbol or another symbol, need to do the same again



I was looking to pre-calculate this in new stream internally in Timebase automatically.
I want to avoid generation of bars from outside of Timebase.

**Comment by alex-karpovich** [comment]
Yes, this is on-demand aggregation

We have functionality called "Materialized Views" for Enterprise Edition. 
https://kb.timebase.info/docs/development/tools/Web%20Admin/admin_guide#materialized-views

looks like this is what you looking for.

Its not pushed to open source yet, but I can try to publish new version in next month.

**Comment by vgwSol** [comment]
Thanks a lot for the quick response 

It will be helpful if you can push this to open source version

**Comment by vgwSol** [comment]
Hi Alex,

Any updates on Materialized Views ?

**Comment by alex-karpovich** [comment]
Hi @vgwSol 
I will be pushing latest changes next week.

**Comment by vgwSol** [comment]
Hi Alex, 
any updates of the PR ?

**Comment by alex-karpovich** [comment]
Hi @vgwSol, ETA is 18 Aug

**Comment by vgwSol** [comment]
Thanks for the update Alex, waiting for it,

**Comment by alex-karpovich** [comment]
Update: ETA - 24 AUG, busy on urgent issues

**Comment by alex-karpovich** [comment]
Published new release https://github.com/epam/TimebaseWS/releases/tag/1.1.2

**Comment by vgwSol** [comment]
Hi Alex

Thanks for followup on this
Will start working on it.

**Comment by alex-karpovich** [comment]
Closing
