### ISSUE TITLE
What branch should be used for PRs?

### ISSUE THREAD

**Issue by joshuaulrich** [finos/TimeBase-CE#240]
The readme isn't clear on which branch we should use as the base branch for PRs. The default branch in the repo is "main", but that branch is currently dozens of commits behind "release-6.1" and even more behind "main-6.1".

**Comment by alex-karpovich** [comment]
default branch is changed to main-6.1
please do any merge requests to it

**Comment by joshuaulrich** [comment]
Thanks!
